const products = [
  {
    imageSrc: "/GENZ-Menu/GENZ/10001.jpg",
    name: "ONEWAY",
    review: "4.5 ★ | 1k",
    price: "Rs. 559",
  },
  {
    imageSrc: "/GENZ-Menu/GENZ/10002.jpg",
    name: "DAMENSCH",
    review: "4.0 ★ | 5k",
    price: "Rs. 479",
  },
  {
    imageSrc: "/GENZ-Menu/GENZ/10003.jpg",
    name: "Flying Machine",
    review: "3.5 ★ | 253",
    price: "Rs. 454",
  },
  {
    imageSrc: "/GENZ-Menu/GENZ/10004.jpg",
    name: "Genzy",
    review: "5 ★ | 500",
    price: "Rs. 549",
  },
  {
    imageSrc: "/GENZ-Menu/GENZ/10005.jpg",
    name: "U.S. Polo Assn.",
    review: "4.5 ★ | 2k",
    price: "Rs. 629",
  },
  {
    imageSrc: "/GENZ-Menu/GENZ/10006.jpg",
    name: "U.S Polo Assn. Denim Co.",
    review: "4.5 ★ | 1.7k",
    price: "Rs. 539",
  },
  {
    imageSrc: "/GENZ-Menu/GENZ/10007.jpg",
    name: "ONEWAY",
    review: "2.5 ★ | 2K",
    price: "Rs. 559",
  },
  {
    imageSrc: "/GENZ-Menu/GENZ/10008.jpg",
    name: "U.S Polo Assn.",
    review: "3 ★ | 352",
    price: "Rs. 599",
  },
  {
    imageSrc: "/GENZ-Menu/GENZ/10009.jpg",
    name: "Flying Machine",
    review: "3.5 ★ | 2.8K",
    price: "Rs. 454",
  },
  {
    imageSrc: "/GENZ-Menu/GENZ/10010.jpg",
    name: "Crazymonk",
    review: "4.5 ★ | 2k",
    price: "Rs. 704",
  },
  {
    imageSrc: "/GENZ-Menu/GENZ/10011.jpg",
    name: "ONEWAY",
    review: "4.5 ★ | 468",
    price: "Rs. 559",
  },
  {
    imageSrc: "/GENZ-Menu/GENZ/10012.jpg",
    name: "Kook N Keech",
    review: "3.5 ★ | 150",
    price: "Rs. 299",
  },
  {
    imageSrc: "/GENZ-Menu/GENZ/10013.jpg",
    name: "U.S Polo Assn.",
    review: "4.5 ★ | 1.2K",
    price: "Rs. 599",
  },
  {
    imageSrc: "/GENZ-Menu/GENZ/10014.jpg",
    name: "Kook N Keech",
    review: "3 ★ | 140",
    price: "Rs. 299",
  },
  {
    imageSrc: "/GENZ-Menu/GENZ/10015.jpg",
    name: "Levis",
    review: "5 ★ | 3k",
    price: "Rs. 599",
  },
  {
    imageSrc: "/GENZ-Menu/GENZ/10016.jpg",
    name: "FCUK",
    review: "2 ★ | 2k",
    price: "Rs. 574",
  },
  {
    imageSrc: "/GENZ-Menu/GENZ/10017.webp",
    name: "HIGHLANDER",
    review: "2.5 ★ | 400",
    price: "Rs. 369",
  },
  {
    imageSrc: "/GENZ-Menu/GENZ/10018.webp",
    name: "Roadster",
    review: "3.5 ★ | 2k",
    price: "Rs. 449",
  },
  {
    imageSrc: "/GENZ-Menu/GENZ/10019.webp",
    name: "Rigo",
    review: "3 ★ | 715k",
    price: "Rs. 599",
  },
  {
    imageSrc: "/GENZ-Menu/GENZ/10020.webp",
    name: "Aero Armour",
    review: "5 ★ | 1k",
    price: "Rs. 794",
  },
  {
    imageSrc: "/GENZ-Menu/GENZ/10021.jpg",
    name: "Aero Armour",
    review: "4.5 ★ | 6k",
    price: "Rs. 794",
  },
  {
    imageSrc: "/GENZ-Menu/GENZ/10022.jpg",
    name: "Maniac",
    review: "4.5 ★ | 2k",
    price: "Rs. 486",
  },
  {
    imageSrc: "/GENZ-Menu/GENZ/10023.jpg",
    name: "max",
    review: "3.5 ★ | 2k",
    price: "Rs. 636",
  },
  {
    imageSrc: "/GENZ-Menu/GENZ/10024.jpg",
    name: "DAMENSCH",
    review: "3 ★ | 586",
    price: "Rs. 647",
  },
  {
    imageSrc: "/GENZ-Menu/GENZ/10025.jpg",
    name: "Roadster",
    review: "4 ★ | 863",
    price: "Rs. 389",
  },
  {
    imageSrc: "/GENZ-Menu/GENZ/10026.jpg",
    name: "DAMENSCH",
    review: "2.5 ★ | 215",
    price: "Rs. 695",
  },
  {
    imageSrc: "/GENZ-Menu/GENZ/10027.jpg",
    name: "kook n keech",
    review: "3.5 ★ | 512",
    price: "Rs. 299",
  },
  {
    imageSrc: "/GENZ-Menu/GENZ/10028.jpg",
    name: "U.S. Polo Assn.",
    review: "3.5 ★ | 1k",
    price: "Rs. 679",
  },
  {
    imageSrc: "/GENZ-Menu/GENZ/10029.jpg",
    name: "Aero Armour",
    review: "4.5 ★ | 6k",
    price: "Rs. 749",
  },
  {
    imageSrc: "/GENZ-Menu/GENZ/10030.jpg",
    name: "Kook N Keech",
    review: "2.5 ★ | 3k",
    price: "Rs. 299",
  },
  {
    imageSrc: "/GENZ-Menu/GENZ/10031.jpg",
    name: "Aero Armour",
    review: "4.5 ★ | 4k",
    price: "Rs. 794",
  },
  {
    imageSrc: "/GENZ-Menu/GENZ/10032.jpg",
    name: "Kook N Keech",
    review: "3 ★ | 5k",
    price: "Rs. 299",
  },
  {
    imageSrc: "/GENZ-Menu/GENZ/10033.jpg",
    name: "ONEWAY",
    review: "4.5 ★ | 1k",
    price: "Rs. 559",
  },
  {
    imageSrc: "/GENZ-Menu/GENZ/10034.jpg",
    name: "DAMENSCH",
    review: "4.0 ★ | 5k",
    price: "Rs. 479",
  },
  {
    imageSrc: "/GENZ-Menu/GENZ/10035.jpg",
    name: "Flying Machine",
    review: "3.5 ★ | 253",
    price: "Rs. 454",
  },
  {
    imageSrc: "/GENZ-Menu/GENZ/10036.jpg",
    name: "Genzy",
    review: "5 ★ | 500",
    price: "Rs. 549",
  },
  {
    imageSrc: "/GENZ-Menu/GENZ/10037.jpg",
    name: "U.S. Polo Assn.",
    review: "4.5 ★ | 2k",
    price: "Rs. 629",
  },
  {
    imageSrc: "/GENZ-Menu/GENZ/10038.jpg",
    name: "U.S Polo Assn. Denim Co.",
    review: "4.5 ★ | 1.7k",
    price: "Rs. 539",
  },
  {
    imageSrc: "/GENZ-Menu/GENZ/10039.jpg",
    name: "ONEWAY",
    review: "2.5 ★ | 2K",
    price: "Rs. 559",
  },
  {
    imageSrc: "/GENZ-Menu/GENZ/10040.jpg",
    name: "U.S Polo Assn.",
    review: "3 ★ | 352",
    price: "Rs. 599",
  },
  {
    imageSrc: "/GENZ-Menu/GENZ/10041.jpg",
    name: "Flying Machine",
    review: "3.5 ★ | 2.8K",
    price: "Rs. 454",
  },
  {
    imageSrc: "/GENZ-Menu/GENZ/10042.jpg",
    name: "Crazymonk",
    review: "4.5 ★ | 2k",
    price: "Rs. 704",
  },
  {
    imageSrc: "/GENZ-Menu/GENZ/10043.jpg",
    name: "ONEWAY",
    review: "4.5 ★ | 468",
    price: "Rs. 559",
  },
  {
    imageSrc: "/GENZ-Menu/GENZ/10044.jpg",
    name: "Kook N Keech",
    review: "3.5 ★ | 150",
    price: "Rs. 299",
  },
  {
    imageSrc: "/GENZ-Menu/GENZ/10045.jpg",
    name: "U.S Polo Assn.",
    review: "4.5 ★ | 1.2K",
    price: "Rs. 599",
  },
  {
    imageSrc: "/GENZ-Menu/GENZ/10046.jpg",
    name: "Kook N Keech",
    review: "3 ★ | 140",
    price: "Rs. 299",
  },
  {
    imageSrc: "/GENZ-Menu/GENZ/10047.jpg",
    name: "Levis",
    review: "5 ★ | 3k",
    price: "Rs. 599",
  },
  {
    imageSrc: "/GENZ-Menu/GENZ/10048.jpg",
    name: "U.S Polo Assn.",
    review: "4.5 ★ | 1.2K",
    price: "Rs. 599",
  },
  {
    imageSrc: "/GENZ-Menu/GENZ/10049.webp",
    name: "Kook N Keech",
    review: "3 ★ | 140",
    price: "Rs. 299",
  },
  {
    imageSrc: "/GENZ-Menu/GENZ/10050.jpg",
    name: "Levis",
    review: "5 ★ | 3k",
    price: "Rs. 599",
  },
];

export default products;
