const products = [
  {
    imageSrc: "/HOME-Menu/HOME/10001.webp",
    name: "ONEWAY",
    review: "4.5 ★ | 1k",
    price: "Rs. 559",
  },
  {
    imageSrc: "/HOME-Menu/HOME/10002.webp",
    name: "DAMENSCH",
    review: "4.0 ★ | 5k",
    price: "Rs. 479",
  },
  {
    imageSrc: "/HOME-Menu/HOME/10003.webp",
    name: "Flying Machine",
    review: "3.5 ★ | 253",
    price: "Rs. 454",
  },
  {
    imageSrc: "/HOME-Menu/HOME/10004.webp",
    name: "Genzy",
    review: "5 ★ | 500",
    price: "Rs. 549",
  },
  {
    imageSrc: "/HOME-Menu/HOME/10005.webp",
    name: "U.S. Polo Assn.",
    review: "4.5 ★ | 2k",
    price: "Rs. 629",
  },
  {
    imageSrc: "/HOME-Menu/HOME/10006.webp",
    name: "U.S Polo Assn. Denim Co.",
    review: "4.5 ★ | 1.7k",
    price: "Rs. 539",
  },
  {
    imageSrc: "/HOME-Menu/HOME/10007.webp",
    name: "ONEWAY",
    review: "2.5 ★ | 2K",
    price: "Rs. 559",
  },
  {
    imageSrc: "/HOME-Menu/HOME/10008.webp",
    name: "U.S Polo Assn.",
    review: "3 ★ | 352",
    price: "Rs. 599",
  },
  {
    imageSrc: "/HOME-Menu/HOME/10009.webp",
    name: "Flying Machine",
    review: "3.5 ★ | 2.8K",
    price: "Rs. 454",
  },
  {
    imageSrc: "/HOME-Menu/HOME/10010.webp",
    name: "Crazymonk",
    review: "4.5 ★ | 2k",
    price: "Rs. 704",
  },
  {
    imageSrc: "/HOME-Menu/HOME/10011.webp",
    name: "ONEWAY",
    review: "4.5 ★ | 468",
    price: "Rs. 559",
  },
  {
    imageSrc: "/HOME-Menu/HOME/10012.webp",
    name: "Kook N Keech",
    review: "3.5 ★ | 150",
    price: "Rs. 299",
  },
  {
    imageSrc: "/HOME-Menu/HOME/10013.webp",
    name: "U.S Polo Assn.",
    review: "4.5 ★ | 1.2K",
    price: "Rs. 599",
  },
  {
    imageSrc: "/HOME-Menu/HOME/10014.webp",
    name: "Kook N Keech",
    review: "3 ★ | 140",
    price: "Rs. 299",
  },
  {
    imageSrc: "/HOME-Menu/HOME/10015.webp",
    name: "Levis",
    review: "5 ★ | 3k",
    price: "Rs. 599",
  },
  {
    imageSrc: "/HOME-Menu/HOME/10016.webp",
    name: "FCUK",
    review: "2 ★ | 2k",
    price: "Rs. 574",
  },
  {
    imageSrc: "/HOME-Menu/HOME/10017.webp",
    name: "HIGHLANDER",
    review: "2.5 ★ | 400",
    price: "Rs. 369",
  },
  {
    imageSrc: "/HOME-Menu/HOME/10018.jpg",
    name: "Roadster",
    review: "3.5 ★ | 2k",
    price: "Rs. 449",
  },
  {
    imageSrc: "/HOME-Menu/HOME/10019.webp",
    name: "Rigo",
    review: "3 ★ | 715k",
    price: "Rs. 599",
  },
  {
    imageSrc: "/HOME-Menu/HOME/10020.webp",
    name: "Aero Armour",
    review: "5 ★ | 1k",
    price: "Rs. 794",
  },
  {
    imageSrc: "/HOME-Menu/HOME/10021.webp",
    name: "Aero Armour",
    review: "4.5 ★ | 6k",
    price: "Rs. 794",
  },
  {
    imageSrc: "/HOME-Menu/HOME/10022.webp",
    name: "Maniac",
    review: "4.5 ★ | 2k",
    price: "Rs. 486",
  },
  {
    imageSrc: "/HOME-Menu/HOME/10023.webp",
    name: "max",
    review: "3.5 ★ | 2k",
    price: "Rs. 636",
  },
  {
    imageSrc: "/HOME-Menu/HOME/10024.webp",
    name: "DAMENSCH",
    review: "3 ★ | 586",
    price: "Rs. 647",
  },
  {
    imageSrc: "/HOME-Menu/HOME/10025.webp",
    name: "Roadster",
    review: "4 ★ | 863",
    price: "Rs. 389",
  },
  {
    imageSrc: "/HOME-Menu/HOME/10026.webp",
    name: "DAMENSCH",
    review: "2.5 ★ | 215",
    price: "Rs. 695",
  },
  {
    imageSrc: "/HOME-Menu/HOME/10027.webp",
    name: "kook n keech",
    review: "3.5 ★ | 512",
    price: "Rs. 299",
  },
  {
    imageSrc: "/HOME-Menu/HOME/10028.webp",
    name: "U.S. Polo Assn.",
    review: "3.5 ★ | 1k",
    price: "Rs. 679",
  },
  {
    imageSrc: "/HOME-Menu/HOME/10029.webp",
    name: "Aero Armour",
    review: "4.5 ★ | 6k",
    price: "Rs. 749",
  },
  {
    imageSrc: "/HOME-Menu/HOME/10030.webp",
    name: "Kook N Keech",
    review: "2.5 ★ | 3k",
    price: "Rs. 299",
  },
  {
    imageSrc: "/HOME-Menu/HOME/10031.webp",
    name: "Aero Armour",
    review: "4.5 ★ | 4k",
    price: "Rs. 794",
  },
  {
    imageSrc: "/HOME-Menu/HOME/10032.webp",
    name: "Kook N Keech",
    review: "3 ★ | 5k",
    price: "Rs. 299",
  },
  {
    imageSrc: "/HOME-Menu/HOME/10033.webp",
    name: "ONEWAY",
    review: "4.5 ★ | 1k",
    price: "Rs. 559",
  },
  {
    imageSrc: "/HOME-Menu/HOME/10034.webp",
    name: "DAMENSCH",
    review: "4.0 ★ | 5k",
    price: "Rs. 479",
  },
  {
    imageSrc: "/HOME-Menu/HOME/10035.webp",
    name: "Flying Machine",
    review: "3.5 ★ | 253",
    price: "Rs. 454",
  },
  {
    imageSrc: "/HOME-Menu/HOME/10036.jpg",
    name: "Genzy",
    review: "5 ★ | 500",
    price: "Rs. 549",
  },
  {
    imageSrc: "/HOME-Menu/HOME/10037.webp",
    name: "U.S. Polo Assn.",
    review: "4.5 ★ | 2k",
    price: "Rs. 629",
  },
  {
    imageSrc: "/HOME-Menu/HOME/10038.webp",
    name: "U.S Polo Assn. Denim Co.",
    review: "4.5 ★ | 1.7k",
    price: "Rs. 539",
  },
  {
    imageSrc: "/HOME-Menu/HOME/10039.webp",
    name: "ONEWAY",
    review: "2.5 ★ | 2K",
    price: "Rs. 559",
  },
  {
    imageSrc: "/HOME-Menu/HOME/10040.webp",
    name: "U.S Polo Assn.",
    review: "3 ★ | 352",
    price: "Rs. 599",
  },
  {
    imageSrc: "/HOME-Menu/HOME/10041.webp",
    name: "Flying Machine",
    review: "3.5 ★ | 2.8K",
    price: "Rs. 454",
  },
  {
    imageSrc: "/HOME-Menu/HOME/10042.webp",
    name: "Crazymonk",
    review: "4.5 ★ | 2k",
    price: "Rs. 704",
  },
  {
    imageSrc: "/HOME-Menu/HOME/10043.webp",
    name: "ONEWAY",
    review: "4.5 ★ | 468",
    price: "Rs. 559",
  },
  {
    imageSrc: "/HOME-Menu/HOME/10044.webp",
    name: "Kook N Keech",
    review: "3.5 ★ | 150",
    price: "Rs. 299",
  },
  {
    imageSrc: "/HOME-Menu/HOME/10045.webp",
    name: "U.S Polo Assn.",
    review: "4.5 ★ | 1.2K",
    price: "Rs. 599",
  },
  {
    imageSrc: "/HOME-Menu/HOME/10046.jpg",
    name: "Kook N Keech",
    review: "3 ★ | 140",
    price: "Rs. 299",
  },
  {
    imageSrc: "/HOME-Menu/HOME/10047.webp",
    name: "Levis",
    review: "5 ★ | 3k",
    price: "Rs. 599",
  },
];

export default products;
