const products = [
  {
    imageSrc: "/KIDS-Menu/KIDS/10001.webp",
    name: "ONEWAY",
    review: "4.5 ★ | 1k",
    price: "Rs. 559",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10002.webp",
    name: "DAMENSCH",
    review: "4.0 ★ | 5k",
    price: "Rs. 479",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10003.webp",
    name: "Flying Machine",
    review: "3.5 ★ | 253",
    price: "Rs. 454",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10004.jpg",
    name: "Genzy",
    review: "5 ★ | 500",
    price: "Rs. 549",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10005.webp",
    name: "U.S. Polo Assn.",
    review: "4.5 ★ | 2k",
    price: "Rs. 629",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10006.webp",
    name: "U.S Polo Assn. Denim Co.",
    review: "4.5 ★ | 1.7k",
    price: "Rs. 539",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10007.webp",
    name: "ONEWAY",
    review: "2.5 ★ | 2K",
    price: "Rs. 559",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10008.webp",
    name: "U.S Polo Assn.",
    review: "3 ★ | 352",
    price: "Rs. 599",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10009.webp",
    name: "Flying Machine",
    review: "3.5 ★ | 2.8K",
    price: "Rs. 454",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10010.jpg",
    name: "Crazymonk",
    review: "4.5 ★ | 2k",
    price: "Rs. 704",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10011.webp",
    name: "ONEWAY",
    review: "4.5 ★ | 468",
    price: "Rs. 559",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10012.webp",
    name: "Kook N Keech",
    review: "3.5 ★ | 150",
    price: "Rs. 299",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10013.webp",
    name: "U.S Polo Assn.",
    review: "4.5 ★ | 1.2K",
    price: "Rs. 599",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10014.jpg",
    name: "Kook N Keech",
    review: "3 ★ | 140",
    price: "Rs. 299",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10015.webp",
    name: "Levis",
    review: "5 ★ | 3k",
    price: "Rs. 599",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10016.jpg",
    name: "FCUK",
    review: "2 ★ | 2k",
    price: "Rs. 574",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10017.webp",
    name: "HIGHLANDER",
    review: "2.5 ★ | 400",
    price: "Rs. 369",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10018.webp",
    name: "Roadster",
    review: "3.5 ★ | 2k",
    price: "Rs. 449",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10019.webp",
    name: "Rigo",
    review: "3 ★ | 715k",
    price: "Rs. 599",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10020.webp",
    name: "Aero Armour",
    review: "5 ★ | 1k",
    price: "Rs. 794",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10021.webp",
    name: "Aero Armour",
    review: "4.5 ★ | 6k",
    price: "Rs. 794",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10022.webp",
    name: "Maniac",
    review: "4.5 ★ | 2k",
    price: "Rs. 486",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10023.webp",
    name: "max",
    review: "3.5 ★ | 2k",
    price: "Rs. 636",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10024.webp",
    name: "DAMENSCH",
    review: "3 ★ | 586",
    price: "Rs. 647",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10025.webp",
    name: "Roadster",
    review: "4 ★ | 863",
    price: "Rs. 389",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10026.webp",
    name: "DAMENSCH",
    review: "2.5 ★ | 215",
    price: "Rs. 695",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10027.webp",
    name: "kook n keech",
    review: "3.5 ★ | 512",
    price: "Rs. 299",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10028.webp",
    name: "U.S. Polo Assn.",
    review: "3.5 ★ | 1k",
    price: "Rs. 679",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10029.webp",
    name: "Aero Armour",
    review: "4.5 ★ | 6k",
    price: "Rs. 749",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10030.webp",
    name: "Kook N Keech",
    review: "2.5 ★ | 3k",
    price: "Rs. 299",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10031.webp",
    name: "Aero Armour",
    review: "4.5 ★ | 4k",
    price: "Rs. 794",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10032.webp",
    name: "Kook N Keech",
    review: "3 ★ | 5k",
    price: "Rs. 299",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10033.jpg",
    name: "ONEWAY",
    review: "4.5 ★ | 1k",
    price: "Rs. 559",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10034.webp",
    name: "DAMENSCH",
    review: "4.0 ★ | 5k",
    price: "Rs. 479",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10035.jpg",
    name: "Flying Machine",
    review: "3.5 ★ | 253",
    price: "Rs. 454",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10036.jpg",
    name: "Genzy",
    review: "5 ★ | 500",
    price: "Rs. 549",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10037.jpg",
    name: "U.S. Polo Assn.",
    review: "4.5 ★ | 2k",
    price: "Rs. 629",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10038.jpg",
    name: "U.S Polo Assn. Denim Co.",
    review: "4.5 ★ | 1.7k",
    price: "Rs. 539",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10039.jpg",
    name: "ONEWAY",
    review: "2.5 ★ | 2K",
    price: "Rs. 559",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10040.jpg",
    name: "U.S Polo Assn.",
    review: "3 ★ | 352",
    price: "Rs. 599",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10041.jpg",
    name: "Flying Machine",
    review: "3.5 ★ | 2.8K",
    price: "Rs. 454",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10042.jpg",
    name: "Crazymonk",
    review: "4.5 ★ | 2k",
    price: "Rs. 704",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10043.jpg",
    name: "ONEWAY",
    review: "4.5 ★ | 468",
    price: "Rs. 559",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10044.jpg",
    name: "Kook N Keech",
    review: "3.5 ★ | 150",
    price: "Rs. 299",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10045.jpg",
    name: "U.S Polo Assn.",
    review: "4.5 ★ | 1.2K",
    price: "Rs. 599",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10046.jpg",
    name: "Kook N Keech",
    review: "3 ★ | 140",
    price: "Rs. 299",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10047.jpg",
    name: "Levis",
    review: "5 ★ | 3k",
    price: "Rs. 599",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10048.jpg",
    name: "FCUK",
    review: "2 ★ | 2k",
    price: "Rs. 574",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10049.jpg",
    name: "HIGHLANDER",
    review: "2.5 ★ | 400",
    price: "Rs. 369",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10050.jpg",
    name: "Roadster",
    review: "3.5 ★ | 2k",
    price: "Rs. 449",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10051.jpg",
    name: "Rigo",
    review: "3 ★ | 715k",
    price: "Rs. 599",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10052.jpg",
    name: "Aero Armour",
    review: "5 ★ | 1k",
    price: "Rs. 794",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10053.jpg",
    name: "Aero Armour",
    review: "4.5 ★ | 6k",
    price: "Rs. 794",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10054.jpg",
    name: "Maniac",
    review: "4.5 ★ | 2k",
    price: "Rs. 486",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10055.jpg",
    name: "max",
    review: "3.5 ★ | 2k",
    price: "Rs. 636",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10056.jpg",
    name: "DAMENSCH",
    review: "3 ★ | 586",
    price: "Rs. 647",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10057.jpg",
    name: "Roadster",
    review: "4 ★ | 863",
    price: "Rs. 389",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10058.jpg",
    name: "DAMENSCH",
    review: "2.5 ★ | 215",
    price: "Rs. 695",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10059.jpg",
    name: "kook n keech",
    review: "3.5 ★ | 512",
    price: "Rs. 299",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10060.jpg",
    name: "U.S. Polo Assn.",
    review: "3.5 ★ | 1k",
    price: "Rs. 679",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10061.jpg",
    name: "Aero Armour",
    review: "4.5 ★ | 6k",
    price: "Rs. 749",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10062.jpg",
    name: "Kook N Keech",
    review: "2.5 ★ | 3k",
    price: "Rs. 299",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10063.jpg",
    name: "Aero Armour",
    review: "4.5 ★ | 4k",
    price: "Rs. 794",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10064.jpg",
    name: "Kook N Keech",
    review: "3 ★ | 5k",
    price: "Rs. 299",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10065.jpg",
    name: "ONEWAY",
    review: "4.5 ★ | 1k",
    price: "Rs. 559",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10066.jpg",
    name: "DAMENSCH",
    review: "4.0 ★ | 5k",
    price: "Rs. 479",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10067.jpg",
    name: "Flying Machine",
    review: "3.5 ★ | 253",
    price: "Rs. 454",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10068.jpg",
    name: "Genzy",
    review: "5 ★ | 500",
    price: "Rs. 549",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10069.jpg",
    name: "U.S. Polo Assn.",
    review: "4.5 ★ | 2k",
    price: "Rs. 629",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10070.jpg",
    name: "U.S Polo Assn. Denim Co.",
    review: "4.5 ★ | 1.7k",
    price: "Rs. 539",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10071.jpg",
    name: "ONEWAY",
    review: "2.5 ★ | 2K",
    price: "Rs. 559",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10072.webp",
    name: "U.S Polo Assn.",
    review: "3 ★ | 352",
    price: "Rs. 599",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10073.jpg",
    name: "Flying Machine",
    review: "3.5 ★ | 2.8K",
    price: "Rs. 454",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10074.jpg",
    name: "Crazymonk",
    review: "4.5 ★ | 2k",
    price: "Rs. 704",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10075.webp",
    name: "Aero Armour",
    review: "4.5 ★ | 6k",
    price: "Rs. 794",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10076.webp",
    name: "Maniac",
    review: "4.5 ★ | 2k",
    price: "Rs. 486",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10077.webp",
    name: "max",
    review: "3.5 ★ | 2k",
    price: "Rs. 636",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10078.webp",
    name: "DAMENSCH",
    review: "3 ★ | 586",
    price: "Rs. 647",
  },
  {
    imageSrc: "/KIDS-Menu/KIDS/10079.webp",
    name: "Roadster",
    review: "4 ★ | 863",
    price: "Rs. 389",
  },
];

export default products;
