import "../../../public/WOMEN-Menu/WOMEN/10001.webp";
const products = [
  {
    imageSrc: "../../../public/WOMEN-Menu/WOMEN/10001.webp",
    name: "ONEWAY",
    review: "4.5 ★ | 1k",
    price: "Rs. 559",
  },
  {
    imageSrc: "../../../public/WOMEN-Menu/WOMEN/10002.webp",
    name: "DAMENSCH",
    review: "4.0 ★ | 5k",
    price: "Rs. 479",
  },
  {
    imageSrc: "../../../public/WOMEN-Menu/WOMEN/10003.webp",
    name: "Flying Machine",
    review: "3.5 ★ | 253",
    price: "Rs. 454",
  },
  {
    imageSrc: "../../../public/WOMEN-Menu/WOMEN/10004.webp",
    name: "Genzy",
    review: "5 ★ | 500",
    price: "Rs. 549",
  },
  {
    imageSrc: "../../../public/WOMEN-Menu/WOMEN/10005.webp",
    name: "U.S. Polo Assn.",
    review: "4.5 ★ | 2k",
    price: "Rs. 629",
  },
  {
    imageSrc: "../../../public/WOMEN-Menu/WOMEN/10006.webp",
    name: "U.S Polo Assn. Denim Co.",
    review: "4.5 ★ | 1.7k",
    price: "Rs. 539",
  },
  {
    imageSrc: "../../../public/WOMEN-Menu/WOMEN/10007.webp",
    name: "ONEWAY",
    review: "2.5 ★ | 2K",
    price: "Rs. 559",
  },
  {
    imageSrc: "../../../public/WOMEN-Menu/WOMEN/10008.webp",
    name: "U.S Polo Assn.",
    review: "3 ★ | 352",
    price: "Rs. 599",
  },
  {
    imageSrc: "../../../public/WOMEN-Menu/WOMEN/10009.webp",
    name: "Flying Machine",
    review: "3.5 ★ | 2.8K",
    price: "Rs. 454",
  },
  {
    imageSrc: "../../../public/WOMEN-Menu/WOMEN/10010.webp",
    name: "Crazymonk",
    review: "4.5 ★ | 2k",
    price: "Rs. 704",
  },
  {
    imageSrc: "../../../public/WOMEN-Menu/WOMEN/10011.webp",
    name: "ONEWAY",
    review: "4.5 ★ | 468",
    price: "Rs. 559",
  },
  {
    imageSrc: "../../../public/WOMEN-Menu/WOMEN/10012.webp",
    name: "Kook N Keech",
    review: "3.5 ★ | 150",
    price: "Rs. 299",
  },
  {
    imageSrc: "../../../public/WOMEN-Menu/WOMEN/10013.webp",
    name: "U.S Polo Assn.",
    review: "4.5 ★ | 1.2K",
    price: "Rs. 599",
  },
  {
    imageSrc: "../../../public/WOMEN-Menu/WOMEN/10014.webp",
    name: "Kook N Keech",
    review: "3 ★ | 140",
    price: "Rs. 299",
  },
  {
    imageSrc: "../../../public/WOMEN-Menu/WOMEN/10015.webp",
    name: "Levis",
    review: "5 ★ | 3k",
    price: "Rs. 599",
  },
  {
    imageSrc: "../../../public/WOMEN-Menu/WOMEN/10016.webp",
    name: "FCUK",
    review: "2 ★ | 2k",
    price: "Rs. 574",
  },
  {
    imageSrc: "../../../public/WOMEN-Menu/WOMEN/10017.webp",
    name: "HIGHLANDER",
    review: "2.5 ★ | 400",
    price: "Rs. 369",
  },
  {
    imageSrc: "../../../public/WOMEN-Menu/WOMEN/10018.webp",
    name: "Roadster",
    review: "3.5 ★ | 2k",
    price: "Rs. 449",
  },
  {
    imageSrc: "../../../public/WOMEN-Menu/WOMEN/10019.webp",
    name: "Rigo",
    review: "3 ★ | 715k",
    price: "Rs. 599",
  },
  {
    imageSrc: "../../../public/WOMEN-Menu/WOMEN/10020.webp",
    name: "Aero Armour",
    review: "5 ★ | 1k",
    price: "Rs. 794",
  },
  {
    imageSrc: "../../../public/WOMEN-Menu/WOMEN/10021.webp",
    name: "Aero Armour",
    review: "4.5 ★ | 6k",
    price: "Rs. 794",
  },
  {
    imageSrc: "../../../public/WOMEN-Menu/WOMEN/10022.webp",
    name: "Maniac",
    review: "4.5 ★ | 2k",
    price: "Rs. 486",
  },
  {
    imageSrc: "../../../public/WOMEN-Menu/WOMEN/10023.webp",
    name: "max",
    review: "3.5 ★ | 2k",
    price: "Rs. 636",
  },
  {
    imageSrc: "../../../public/WOMEN-Menu/WOMEN/10024.webp",
    name: "DAMENSCH",
    review: "3 ★ | 586",
    price: "Rs. 647",
  },
  {
    imageSrc: "../../../public/WOMEN-Menu/WOMEN/10025.webp",
    name: "Roadster",
    review: "4 ★ | 863",
    price: "Rs. 389",
  },
  {
    imageSrc: "../../../public/WOMEN-Menu/WOMEN/10026.webp",
    name: "DAMENSCH",
    review: "2.5 ★ | 215",
    price: "Rs. 695",
  },
  {
    imageSrc: "../../../public/WOMEN-Menu/WOMEN/10027.webp",
    name: "kook n keech",
    review: "3.5 ★ | 512",
    price: "Rs. 299",
  },
  {
    imageSrc: "../../../public/WOMEN-Menu/WOMEN/10028.webp",
    name: "U.S. Polo Assn.",
    review: "3.5 ★ | 1k",
    price: "Rs. 679",
  },
  {
    imageSrc: "../../../public/WOMEN-Menu/WOMEN/10029.webp",
    name: "Aero Armour",
    review: "4.5 ★ | 6k",
    price: "Rs. 749",
  },
  {
    imageSrc: "../../../public/WOMEN-Menu/WOMEN/10030.webp",
    name: "Kook N Keech",
    review: "2.5 ★ | 3k",
    price: "Rs. 299",
  },
  {
    imageSrc: "../../../public/WOMEN-Menu/WOMEN/10031.webp",
    name: "Aero Armour",
    review: "4.5 ★ | 4k",
    price: "Rs. 794",
  },
  {
    imageSrc: "../../../public/WOMEN-Menu/WOMEN/10032.webp",
    name: "Kook N Keech",
    review: "3 ★ | 5k",
    price: "Rs. 299",
  },
  {
    imageSrc: "../../../public/WOMEN-Menu/WOMEN/10033.webp",
    name: "Kook N Keech",
    review: "2.5 ★ | 3k",
    price: "Rs. 299",
  },
  {
    imageSrc: "../../../public/WOMEN-Menu/WOMEN/10034.webp",
    name: "Aero Armour",
    review: "4.5 ★ | 4k",
    price: "Rs. 794",
  },
  {
    imageSrc: "../../../public/WOMEN-Menu/WOMEN/10035.webp",
    name: "Kook N Keech",
    review: "3 ★ | 5k",
    price: "Rs. 299",
  },
  {
    imageSrc: "../../../public/WOMEN-Menu/WOMEN/10036.webp",
    name: "FCUK",
    review: "2 ★ | 2k",
    price: "Rs. 574",
  },
  {
    imageSrc: "../../../public/WOMEN-Menu/WOMEN/10037.webp",
    name: "HIGHLANDER",
    review: "2.5 ★ | 400",
    price: "Rs. 369",
  },
  {
    imageSrc: "../../../public/WOMEN-Menu/WOMEN/10038.webp",
    name: "Roadster",
    review: "3.5 ★ | 2k",
    price: "Rs. 449",
  },
  {
    imageSrc: "../../../public/WOMEN-Menu/WOMEN/10039.webp",
    name: "Rigo",
    review: "3 ★ | 715k",
    price: "Rs. 599",
  },
  {
    imageSrc: "../../../public/WOMEN-Menu/WOMEN/10040.webp",
    name: "Aero Armour",
    review: "5 ★ | 1k",
    price: "Rs. 794",
  },
  {
    imageSrc: "../../../public/WOMEN-Menu/WOMEN/10041.webp",
    name: "Aero Armour",
    review: "4.5 ★ | 6k",
    price: "Rs. 794",
  },
  {
    imageSrc: "../../../public/WOMEN-Menu/WOMEN/10042.webp",
    name: "Maniac",
    review: "4.5 ★ | 2k",
    price: "Rs. 486",
  },
  {
    imageSrc: "../../../public/WOMEN-Menu/WOMEN/10043.webp",
    name: "max",
    review: "3.5 ★ | 2k",
    price: "Rs. 636",
  },
  {
    imageSrc: "../../../public/WOMEN-Menu/WOMEN/10044.webp",
    name: "DAMENSCH",
    review: "3 ★ | 586",
    price: "Rs. 647",
  },
  {
    imageSrc: "../../../public/WOMEN-Menu/WOMEN/10045.webp",
    name: "Roadster",
    review: "4 ★ | 863",
    price: "Rs. 389",
  },
  {
    imageSrc: "../../../public/WOMEN-Menu/WOMEN/10046.webp",
    name: "DAMENSCH",
    review: "2.5 ★ | 215",
    price: "Rs. 695",
  },
  {
    imageSrc: "../../../public/WOMEN-Menu/WOMEN/10047.webp",
    name: "kook n keech",
    review: "3.5 ★ | 512",
    price: "Rs. 299",
  },
  {
    imageSrc: "../../../public/WOMEN-Menu/WOMEN/10048.webp",
    name: "U.S. Polo Assn.",
    review: "3.5 ★ | 1k",
    price: "Rs. 679",
  },
  {
    imageSrc: "../../../public/WOMEN-Menu/WOMEN/10049.webp",
    name: "Aero Armour",
    review: "4.5 ★ | 6k",
    price: "Rs. 749",
  },
  {
    imageSrc: "../../../public/WOMEN-Menu/WOMEN/10050.webp",
    name: "Kook N Keech",
    review: "2.5 ★ | 3k",
    price: "Rs. 299",
  },
];

export default products;
